[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run preview"

[[services]]
name = "codeoven-frontend"

[services.build]
buildCommand = "npm ci && npm run build"

[services.deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10